# -*- coding: utf-8 -*-
"""Untitled91.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lSqpbx4EpCWjym5Ewkh2CFXQ5ESzT4vs
"""

# Simulating mobile app behavior under different conditions

import time
import random

class MobileAppSimulator:
    def __init__(self):
        self.battery_level = 100
        self.network_strength = 100
        self.device_config = "default"

    def simulate_low_battery(self):
        self.battery_level = random.randint(1, 15)
        print(f"Simulating low battery: {self.battery_level}%")
        return self.battery_level

    def simulate_poor_network(self):
        self.network_strength = random.randint(0, 20)
        print(f"Simulating poor network: {self.network_strength}% signal")
        return self.network_strength

    def simulate_device_config(self, config):
        self.device_config = config
        print(f"Simulating on device config: {self.device_config}")
        return self.device_config

    def run_app(self):
        print("Running app with simulated conditions...")
        if self.battery_level < 10:
            print("⚠️  App warning: Low battery mode enabled.")
        if self.network_strength < 10:
            print("⚠️  App warning: Network connectivity is very poor.")
        if self.device_config != "default":
            print(f"ℹ️  Adjusting settings for device config: {self.device_config}")

        # Simulate app response time
        simulated_delay = (100 - self.network_strength) / 50 + random.random()
        print(f"Simulated response time: {simulated_delay:.2f} seconds")

        # Simulate app crash probability
        crash_chance = 0.1 if self.battery_level < 10 else 0.02
        if random.random() < crash_chance:
            print("❌ App crashed due to unstable conditions.")
        else:
            print("✅ App ran successfully under current conditions.\n")

# Simulate reliability tests
app = MobileAppSimulator()

# Test 1: Low Battery
app.simulate_low_battery()
app.run_app()

# Test 2: Poor Network
app.simulate_poor_network()
app.run_app()

# Test 3: Low Battery + Poor Network + Different Device Config
app.simulate_low_battery()
app.simulate_poor_network()
app.simulate_device_config("low_ram_device")
app.run_app()